# Generated by Django 4.0.1 on 2022-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
