# Generated by Django 4.0.1 on 2022-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, default="", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
