# Generated by Django 4.0.1 on 2022-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
        ('core_user', '0005_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments_liked",
            field=models.ManyToManyField(
                related_name="commented_by", to="core_comment.Comment"
            ),
        ),
    ]
